cost_function_name_default: default
# Default value is used if controller does not specify a cost_function_specification (leave empty)
# Cost functions are grouped by environment name in a folder within Control_Toolkit_ASF.Cost_Functions
# Check config.yml to learn more on how cost_functions are selected

<<EnvironmentName>>:
  <<cost_function_name>>:
    # Add any required parameters used by your cost function like so:
    <<parameter>>: <<value>>

# Full example:
# CartPole:
#   quadratic_boundary_grad:
#     dd_weight: 600.0
#     ep_weight: 20000.0
#     ekp_weight: 80.0
#     cc_weight: 1.0
#     ccrc_weight: 1.0
#     R: 1.0
